services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg libopenh264-6
      pip install -r requirements.txt
    startCommand: python app.py
